FROM mongo:3.4.6

MAINTAINER jdubowy@gmail.com

ARG COUNTRY=US
ARG STATE=WA
ARG CITY=Seattle
ARG ORGANIZATION=FooBar

COPY generate-ssl-cert.sh /usr/local/bin/
RUN /usr/local/bin/generate-ssl-cert.sh \
    -r /etc/ssl/ -n mongod -c $COUNTRY -s $STATE \
    -l $CITY -o $ORGANIZATION -u BlueSkyWeb
