FROM mongo:4.2.24

MAINTAINER jdubowy@gmail.com

ARG COUNTRY
ARG STATE
ARG CITY
ARG ORGANIZATION

COPY generate-ssl-cert.sh /usr/local/bin/
RUN /usr/local/bin/generate-ssl-cert.sh \
    -r /etc/ssl/ -n mongod -c $COUNTRY -s $STATE \
    -l $CITY -o $ORGANIZATION -u BlueSkyWeb
