#!/usr/bin/env bash

show_help=false
rebuild=false
clear_data=false
yaml_file=dev/docker-compose.yml
shut_down=false

while [ -n "$1" ]; do # while loop starts
    case "$1" in
    -h) show_help=true && shift ;;
    --help) show_help=true && shift ;;
    --rebuild) rebuild=true && shift ;;
    --clear-data) clear_data=true && shift ;;
    --yaml-file) yaml_file="$2" && shift && shift ;;
    --shut-down) shut_down=true && shift ;;
    *) echo "Option $1 not recognized" && exit 1 ;;
    esac
done

if [ "$show_help" = true ] ; then
    echo ""
    echo "Options:"
    echo "   -h/--help     - show this help message"
    echo "   --rebuild     - rebuild docker images"
    echo "   --clear-data  - delete mongodb, rabbitmq, and output data"
    echo "   --yaml-file   - default: dev/docker-compose-dev.yml"
    echo "   --shut-down   - don't restart"
    echo ""
    echo "Usage:"
    echo "   $0"
    echo "   $0 --yaml-file dev/docker-compose.yml --rebuild --clear-data"
    echo "   $0 --shut-down"
    echo ""
    exit 0
fi

if [ ! -e $yaml_file ]; then
    echo "ERROR:  docker-compose YAML file doesn't exist"
    echo "ERROR:     $yaml_file"
    exit 1
fi

echo "Options"
echo "  Rebuild docker images: $rebuild"
echo "  Clear data: $clear_data"
echo "  docker-compose YAML file: $yaml_file"

bluesky_version=$(head -n 1 .bluesky-version)
echo "Using bluesky version $bluesky_version"
cat Dockerfile-unversioned |sed -e "s/__BLUESKY_VERSION__/$bluesky_version/g" > Dockerfile

# call `down` on all known yaml files, in case previously used yaml file
# is different than this one.
docker-compose -p bluesky-web -f dev/docker-compose.yml down --remove-orphans
docker-compose -p bluesky-web -f $yaml_file down --remove-orphans
if [ "$rebuild" = true ] ; then
    sudo chown -R $UID dev/data/
    sudo rm dev/data/rabbitmq/.erlang.cookie
    find . -name __pycache__ -exec sudo rm -r {} \;
    find . -name '.pytest_cache' -exec sudo rm -r {} \;
    docker build -t bluesky-web . \
        --build-arg COUNTRY=US --build-arg STATE=WA \
        --build-arg CITY=Seattle --build-arg ORGANIZATION=FooBar
    docker build -t bluesky-web-nginx -f Dockerfile-nginx .
    docker build -t bluesky-web-mongo -f Dockerfile-mongo .\
        --build-arg COUNTRY=US --build-arg STATE=WA \
        --build-arg CITY=Seattle --build-arg ORGANIZATION=FooBar
    docker build -t bluesky-web-rabbitmq -f Dockerfile-rabbitmq .\
        --build-arg COUNTRY=US --build-arg STATE=WA \
        --build-arg CITY=Seattle --build-arg ORGANIZATION=FooBar
fi
if [ "$clear_data" = true ] ; then
    sudo rm -r dev/data/*
fi
if [ "$shut_down" = false ] ; then
    mkdir -p ./dev/logs/mongodb/ ./dev/logs/web/ \
        ./dev/logs/worker/dri ./dev/logs/worker/nam \
        ./dev/logs/worker/no-met ./dev/data/mongodb/db \
        ./dev/data/output
    docker-compose -p bluesky-web -f $yaml_file up
fi
