#! /usr/bin/env python

__author__ = "Joel Dubowy"
__copyright__ = "Copyright 2015, AirFire, PNW, USFS"

import json
import sys

from afscripting import args as scripting_args

try:
    import blueskyconfig
except:
    import os
    root_dir = os.path.abspath(os.path.join(sys.path[0], '../../'))
    sys.path.insert(0, root_dir)
    import blueskyconfig


# Note: the trailing space seems to be the only way to add an extra trailing line
EPILOG_STR = """
Examples

   $ {script_name}
   $ {script_name} --config-file ./dev/config.json

Example curl Requests

    $ curl "http://localhost:8887/blueskyweb/api/ping/"
 """.format(script_name=sys.argv[0])

if __name__ == "__main__":
    parser, args = scripting_args.parse_args([], [], epilog=EPILOG_STR,
        support_configuration_options_short_names=True)

    blueskyconfig.apply_overrides(args.config_file_options)
    blueskyconfig.apply_overrides(args.config_options)

    sys.stdout.write(json.dumps(blueskyconfig.config, sort_keys=True, indent=2))
